# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-14 05:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20161214_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='pledge_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 12, 14, 5, 48, 23, 852546), verbose_name='pledge date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='subscription_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='subscription date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='validation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 12, 14, 5, 48, 30, 716362), verbose_name='validation date'),
            preserve_default=False,
        ),
    ]
