# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-14 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20161214_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='validation_date',
            field=models.DateField(blank=True, null=True, verbose_name='validation date'),
        ),
    ]
