# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-12 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image_heigth', models.CharField(max_length=10)),
                ('image_width', models.CharField(max_length=10)),
                ('image_title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Image')),
            ],
            options={
                'verbose_name': 'home display',
                'verbose_name_plural': 'home displays',
            },
        ),
    ]
